layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: frankker
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: frankker
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://frankker.tech
  # youtube: your_username

topics:
  - name: AWS
    web_url: https://github.com/aws
    image_url: https://frankker-github.s3.eu-central-1.amazonaws.com/aws.jpg

  - name: Python
    web_url: https://github.com/python
    image_url: https://frankker-github.s3.eu-central-1.amazonaws.com/Python-logo-black.png

  - name: Apache Kafka
    web_url: https://github.com/apache/kafka
    image_url: https://frankker-github.s3.eu-central-1.amazonaws.com/kafka.png

certificates:
  - name: AWS Certified Solutions Architect – Professional
    web_url: https://www.credly.com/badges/7025d279-40e5-4c66-a216-009e8e05400f
    image_url: https://frankker-github.s3.eu-central-1.amazonaws.com/aws.jpg

  - name: AWS Certified SysOps Administrator – Associate
    web_url: https://www.credly.com/badges/b5b9b1c9-a12f-4966-a54a-3f5b5b2358f5
    image_url: https://frankker-github.s3.eu-central-1.amazonaws.com/aws.jpg

  - name: AWS Certified Developer – Associate
    web_url: https://www.credly.com/badges/47ee5a04-a429-48b4-9479-a8d2434bf374
    image_url: https://frankker-github.s3.eu-central-1.amazonaws.com/aws.jpg

  - name: AWS Certified Solutions Architect – Associate
    web_url: https://www.credly.com/earner/earned/share/cdd8a9d8-3d09-4e30-b08e-71c8c0ca2865
    image_url: https://frankker-github.s3.eu-central-1.amazonaws.com/aws.jpg

  - name: Oracle Certified Associate, Java SE 8 Programmer
    web_url: https://www.credly.com/badges/b5f58c5b-0386-4ff4-823d-cd9e332d691b
    image_url: https://frankker-github.s3.eu-central-1.amazonaws.com/Oracle_Associates_Badge__1_.png